### ISSUE TITLE
How to save and get a list or array?

### ISSUE THREAD

**Issue by StevenLOL** [ifduyue/pyssdb#12]
Hi, is there a way to save and get a list or array?

**Comment by ifduyue** [comment]
Did you figure it out?

a) set/get serialized list/array
b) use list-relating commands http://ssdb.io/docs/commands/index.html#list

**Comment by StevenLOL** [comment]
@ifduyue thanks.

I took the first approach, dump my object(list/array) to a key/value set through pickle.
