### ISSUE TITLE
a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by markqiu** [ifduyue/pyssdb#13]
TypeErrorTraceback (most recent call last)
<ipython-input-20-b4724815d3b7> in <module>()
      2 import pyssdb
      3 ssdb = pyssdb.Client()
----> 4 ssdb.set('key', 'value')
      5 print(ssdb.hget('1','1'))

/opt/conda/lib/python3.5/site-packages/pyssdb.py in execute_command(self, cmd, *args)
    175         connection = self.connection_pool.get_connection()
    176         try:
--> 177             connection.send(cmd, *args)
    178             data = connection.recv()
    179         except:

/opt/conda/lib/python3.5/site-packages/pyssdb.py in send(self, cmd, *args)
     75             args = args[:-1] + (str(args[-1]), )
     76         buf = ''.join('%d\n%s\n' % (len(i), i) for i in args) + '\n'
---> 77         self._sock.sendall(buf)
     78 
     79     def recv(self):

TypeError: a bytes-like object is required, not 'str'

**Comment by ifduyue** [comment]
pyssdb doesn't work with Python3 right now.

**Comment by markqiu** [comment]
I changed  line 77 to solve the problem.  self._sock.sendall(buf.encode('utf-8')).

**Comment by ifduyue** [comment]
@markqiu Thanks, I've made a new release https://pypi.python.org/pypi/pyssdb/0.2
