### ISSUE TITLE
不支持python3.4会报错

### ISSUE THREAD

**Issue by xingyunxlm** [ifduyue/pyssdb#18]
File "/usr/lib/python3.4/site-packages/pyssdb.py", line 98, in <genexpr>
    buf = utf8('').join(utf8('%d\n%s\n') % (len(i), i) for i in args) + utf8('\n')
TypeError: unsupported operand type(s) for %: 'bytes' and 'tuple'

**Comment by ifduyue** [comment]
@xingyunxlm did you solve this issue?

**Comment by xingyunxlm** [comment]
I upgraded to 3.5

**Comment by ifduyue** [comment]
I checked and confirmed that this is a issue with Python 3.4, but I don't want to spend time to solve this issue.
People barely use Python 3.4. pyssdb supports only Python 2.6/2.7/3.5/3.6
@xingyunxlm Thanks for reporting.

**Comment by xingyunxlm** [comment]
I see，thank you
