### ISSUE TITLE
python3.4 error set zset error

### ISSUE THREAD

**Issue by vscz** [ifduyue/pyssdb#19]
I install pyssdb via pip, when i run test, is something wrong.
mycode：
`
import pyssdb

conn = pyssdb.Client(host='127.0.0.1', port=8888)

conn.set('test_key1', 'val')

val1 = conn.get('test_key1')

print('val1')
print(val1)
`

ERROR:
`
Traceback (most recent call last):
  File "test_ssdb.py", line 5, in <module>
    conn.set('test_key1', 'val')
  File "/usr/local/lib/python3.4/dist-packages/pyssdb.py", line 191, in wrapper
    data = func(self, cmd, *args)
  File "/usr/local/lib/python3.4/dist-packages/pyssdb.py", line 215, in execute_command
    connection.send(cmd, *args)
  File "/usr/local/lib/python3.4/dist-packages/pyssdb.py", line 98, in send
    buf = utf8('').join(utf8('%d\n%s\n') % (len(i), i) for i in args) + utf8('\n')
  File "/usr/local/lib/python3.4/dist-packages/pyssdb.py", line 98, in <genexpr>
    buf = utf8('').join(utf8('%d\n%s\n') % (len(i), i) for i in args) + utf8('\n')
TypeError: unsupported operand type(s) for %: 'bytes' and 'tuple'
`
ERROR CODE:
`
    def send(self, cmd, *args):
        if cmd == 'delete':
            cmd = 'del'
        self.last_cmd = cmd
        if self._sock is None:
            self.connect()

        args = [utf8(cmd)] + [utf8(i) for i in args]
        buf = utf8('').join(utf8('%d\n%s\n') % (len(i), i) for i in args) + utf8('\n') # ERROR IN HRER
        self._sock.sendall(buf)
`

**Comment by ifduyue** [comment]
@vscz Hello, pyssdb doesn't support Python3.4, try using Python 3.5/3.6

**Comment by vscz** [comment]
It works where I am using Python3.6, Thanks!
