### ISSUE TITLE
pyssdb执行info问题 。

### ISSUE THREAD

**Issue by big-loser** [ifduyue/pyssdb#4]
> > > c = pyssdb.Client(host='10.1.1.195', port=8888)
> > > print c.info()

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.6/site-packages/pyssdb.py", line 178, in execute_command
    data = connection.recv()
  File "/usr/lib/python2.6/site-packages/pyssdb.py", line 111, in recv
    raise error(*ret)
pyssdb.error: ('ssdb-server', 'version', '1.7.0.0', 'links', '56', 'total_calls', '43393007090', 'key_range.kv', '"00.2010.10000027.web.s" - "ff.2110.9999571.s"', 'key_range.hash', '"00.2008.10637.h" - "ff.210a.990636.h"', 'key_range.zset', '"00.2001.10190.z" - "ff.2202.943419.z"', 'key_range.list', '"" - ""', 'leveldb.stats', '                               Compactions\nLevel  Files Size(MB) Time(sec) Read(MB) Write(MB)\n--------------------------------------------------\n  0        0        0     11640        0    153316\n  1        2       77     68340   257726    851003\n  2       24      869    241859  2878129   2610000\n  3      237     8764   3697703 66426608  65991863\n  4      725    23157    462730  9333490   9320137\n')

这样是否正常 ？

**Comment by ifduyue** [comment]
看来 info 命令需要特别对待

**Comment by ifduyue** [comment]
@big-loser 从文档 http://ssdb.io/docs/commands/info.html 和 http://ssdb.io/docs/ssdb-cli.html 来看，这个命令主要是在 cli 下使用的。

使用 SSDB.php 输出 info:

```php
<?php

require 'SSDB.php';

$ssdb = new SSDB('127.0.0.1', 8888);
var_dump($ssdb->info());
```
```txt
object(SSDB_Response)#2 (4) {
  ["cmd"]=>
  string(4) "info"
  ["code"]=>
  string(2) "ok"
  ["data"]=>
  array(17) {
    [0]=>
    string(11) "ssdb-server"
    [1]=>
    string(7) "version"
    [2]=>
    string(5) "1.9.4"
    [3]=>
    string(5) "links"
    [4]=>
    string(1) "1"
    [5]=>
    string(11) "total_calls"
    [6]=>
    string(2) "16"
    [7]=>
    string(6) "dbsize"
    [8]=>
    string(8) "30270545"
    [9]=>
    string(7) "binlogs"
    [10]=>
    string(69) "    capacity : 20000000
    min_seq  : 781339
    max_seq  : 20781342"
    [11]=>
    string(14) "serv_key_range"
    [12]=>
    string(71) "    kv  : "" - ""
    hash: "" - ""
    zset: "" - ""
    list: "" - """
    [13]=>
    string(14) "data_key_range"
    [14]=>
    string(101) "    kv  : "A" - "\xe4\xb8\xad\xe6\x96\x87"
    hash: "" - ""
    zset: "0" - "9999"
    list: "" - """
    [15]=>
    string(13) "leveldb.stats"
    [16]=>
    string(298) "                               Compactions
Level  Files Size(MB) Time(sec) Read(MB) Write(MB)
--------------------------------------------------
  0        3       30         0        0         0
  1        7      131         0        0         0
  2        4      141         0        0         0
"
  }
  ["message"]=>
  NULL
}
```

**Comment by ifduyue** [comment]
@big-loser 现在返回 info 命令的数据了，勉强能看，也可能需要自己解析。

```
['version', '1.9.4', 'links', '1', 'total_calls', '6', 'dbsize', '17454752', 'binlogs', '    capacity : 20000000\n    min_seq  : 40627119\n    max_seq  : 60627119', 'serv_key_range', '    kv  : "" - ""\n    hash: "" - ""\n    zset: "" - ""\n    list: "" - ""', 'data_key_range', '    kv  : "A" - "\\xe4\\xb8\\xad\\xe6\\x96\\x87"\n    hash: "" - ""\n    zset: "0" - "9999"\n    list: "" - ""', 'leveldb.stats', '                               Compactions\nLevel  Files Size(MB) Time(sec) Read(MB) Write(MB)\n--------------------------------------------------\n  0        1        1         0        0         1\n  1        7      133         0        0         0\n  2        5      158         0        0         0\n']```
